---
title: "player_game"
author: "James Drury"
date: "2024-04-14"
output: html_document
---

```{r}
source("setup.R")
```

### load game
```{r load game data to environment}

box_scores(
  game_ids = c(21700002)
)

d <- dataBoxScorePlayerNBA


bref_players_stats(seasons = 2019)

teams_tables(all_active_teams = TRUE,
             seasons = 2022:2023,
             # teams = "Phoenix Suns",
             tables = c("player"),
             modes = c("PerGame", "Per100Possessions"),
             measures = c("Base", "Advanced"))


# write_rds(dataPlayerTeamBase, "dataPlayerTeamBase_2022_2023.rds")
# write_rds(dataPlayerTeamAdvanced, "dataPlayerTeamAdvanced_2022_2023.rds")

db <- read_rds("dataPlayerTeamBase_2022_2023.rds")
d_base_team <- db %>%
  filter(nameTable == "TeamOverall")
d_base_player <- db %>%
  filter(nameTable == "PlayersSeasonTotals")
da <- read_rds("dataPlayerTeamAdvanced_2022_2023.rds")
d_adv_team <- da %>%
  filter(nameTable == "TeamOverall" & modeSearch == "PerGame") %>%
  mutate(netrtg = ortg - drtg,
         netrtgE = ortgE - drtgE)
d_adv_player <- da %>%
  filter(nameTable == "PlayersSeasonTotals")
```

### DEV: both team shooting barplot
```{r}
d %>%
  arrange(slugTeam) %>%
  group_by(slugTeam) %>%
  top_n(n = 3, wt = pts) %>%
  ungroup() %>%
  pivot_longer(cols = c("fga", "fgm", "fta", "ftm", "fg2a", "fg2m", "fg3m", "fg3a"), 
               names_to = "made_miss",
               values_to = "value") %>%
  mutate(shot_type = case_when(
    made_miss %in% c("fga", "fgm") ~ "All FGs",
    made_miss %in% c("fg2a", "fg2m") ~ "2-pt FGs",
    made_miss %in% c("fg3a", "fg3m") ~ "3-pt FGs",
    made_miss %in% c("fta", "ftm") ~ "FTs"
  )) %>%
  ggplot(aes(x = shot_type, y = value)) +
  geom_bar(data = . %>% filter(made_miss %in% c("fg3a", "fg2a", "fta")),
           aes(fill = "Shots taken"),
           color = "darkolivegreen3",
           alpha = 0.5,
           stat = "identity",
           position = "dodge") +
  geom_bar(data = . %>% filter(made_miss %in% c("fg3m", "fg2m", "ftm")),
           aes(fill = "Shots made"),
           stat = "identity",
           position = "dodge") +
  facet_wrap(namePlayer ~ pts) +
  theme_minimal() +
  scale_fill_manual(values = c("Shots made" = "darkolivegreen3", 
                               "Shots taken" = "gray")) +
  labs(x = "",
       y = "Shots",
       fill = "")


```

### PROD: both teams shooting barplot
```{r}

both_team_shooting_barplot <- function() {

  d %>%
    arrange(slugTeam) %>%
    group_by(slugTeam) %>%
    top_n(n = 3, wt = pts) %>%
    ungroup() %>%
    pivot_longer(cols = c("fga", "fgm", "fta", "ftm", "fg2a", "fg2m", "fg3m", "fg3a"), 
                 names_to = "made_miss",
                 values_to = "value") %>%
    mutate(shot_type = case_when(
      made_miss %in% c("fga", "fgm") ~ "All FGs",
      made_miss %in% c("fg2a", "fg2m") ~ "2-pt FGs",
      made_miss %in% c("fg3a", "fg3m") ~ "3-pt FGs",
      made_miss %in% c("fta", "ftm") ~ "FTs"
    )) %>%
    ggplot(aes(x = shot_type, y = value)) +
    geom_bar(data = . %>% filter(made_miss %in% c("fg3a", "fg2a", "fta")),
             aes(fill = "Shots taken"),
             color = "darkolivegreen3",
             alpha = 0.5,
             stat = "identity",
             position = "dodge") +
    geom_bar(data = . %>% filter(made_miss %in% c("fg3m", "fg2m", "ftm")),
             aes(fill = "Shots made"),
             stat = "identity",
             position = "dodge") +
    facet_wrap(namePlayer ~ pts) +
    theme_minimal() +
    scale_fill_manual(values = c("Shots made" = "darkolivegreen3", 
                                 "Shots taken" = "gray")) +
    labs(x = "",
         y = "Shots",
         fill = "")
  
}

```


### DEV: Select a team and put that team in context to the overall league
```{r}





teamTable_fnc <- function(team) {
  d_adv_team %>%
    filter(yearSeason == 2022) %>%
    mutate(ortgRank = rank(-ortg),
           drtgRank = rank(-drtg),
           netrtgRank = rank(-netrtg),
           pctTS = percent(pctTS)) %>%
    filter(nameTeam == team) %>%
    select("Team" = nameTeam, 
           "Wins" = wins, 
           "True Shooting %" = pctTS, 
           "Offensive Rating" = ortg,
           "Defensive Rating" = drtg,
           "Net Rating" = netrtg,
           "Offensive Rating (rank)" = ortgRank,
           "Defensive Rating (rank)" = drtgRank,
           "Net Rating (rank)" = netrtgRank)
}





x <- d_adv_team %>%
  group_by(yearSeason) %>%
  filter(modeSearch == "PerGame") %>%
  summarize(across(c(ortg, pctTS, pctOREB, pctDREB, pace),
                   ~ mean(.)))


```

